### ISSUE TITLE
Migrate to maven.imagej.net

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/maven#2]
Deploying to https://maven.imagej.net via travis is pretty simple now: https://imagej.net/Travis

Pros:
 - Users do not need to add additional repository to `pom.xml`
 - deployment is super easy (`scijava-scripts/release-version.sh `)

Cons:
 - ? Do not see any so far

**Comment by igorpisarev** [comment]
I agree that it's a good idea. Many of the released packages here are well-tested and mature enough to be published in the imagej repository (such as various n5 artifacts)

**Comment by axtimwalde** [comment]
Done for everything well tested.
